spring:
  rabbitmq:
    host: cougar.rmq.cloudamqp.com
    port: 5672
    username: lvtyxxuy
    virtual-host: lvtyxxuy
    password: HFPrV1eq1gLSAjQ0E_0mo5WDGgeLx-uj

server.port: 8081

wallet-service: http://localhost:8080